# Generated by Django 3.2 on 2025-12-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='电话号码')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (0, '女')], verbose_name='性别')),
            ],
        ),
    ]
