"""
Django settings for ormsingletable project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&72(lofy*4xa68%0cl8k$l3g5y-*272@ybfh)+9@-&ntx45%v5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    # ———————— 核心功能（谨慎移除）————————

    # 'django.contrib.admin',        # 后台管理界面 → 不需要 Web 管理后台可注释
    # 'django.contrib.auth',         # 用户认证系统（User/Group 模型等）→ 若不用登录/权限可注释
    'django.contrib.contenttypes',  # 内容类型框架（GenericForeignKey 必需）→ 若用到外键泛化（如评论系统）则保留，否则可注释
    # 'django.contrib.sessions',     # 会话支持（基于 cookie 或 DB）→ 无状态 API（如 JWT）可注释
    'django.contrib.messages',  # 消息框架（如表单成功提示）→ 若前端不依赖 Django 消息可注释
    'django.contrib.staticfiles',  # 静态文件收集（开发时 serve static）→ 若纯 API 且静态文件由 Nginx 托管，可注释

    # ———————— 你的应用 ————————
    'apps.user',  # 你的自定义 app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',  # 安全头（如 HTTPS 强制）→ 建议保留
    # 'django.contrib.sessions.middleware.SessionMiddleware',  # 会话中间件 → 无 session 可注释
    'django.middleware.common.CommonMiddleware',  # 处理 APPEND_SLASH、DISALLOWED_USER_AGENTS 等 → 建议保留
    'django.middleware.csrf.CsrfViewMiddleware',  # CSRF 保护 → 若为纯 API（无浏览器表单提交），可注释！
    # 'django.contrib.auth.middleware.AuthenticationMiddleware', # 登录用户注入 request.user → 无 auth 可注释
    # 'django.contrib.messages.middleware.MessageMiddleware',    # 消息闪现 → 无 messages 可注释
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # 防点击劫持 → 建议保留（安全）
]

ROOT_URLCONF = 'ormsingletable.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                # 'django.contrib.auth.context_processors.auth',
                # 'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ormsingletable.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# tips:指定mysql作为我们的数据库
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'djorm',
        'HOST': 'localhost',
        'PORT': 3306,
        'USER': 'root',
        'PASSWORD': 'HHCzio20',
        'POOL_OPTIONS': {
            'POOL_SIZE': 10,  # 最小数量
            'MAX_OVERFLOW': 10,  # 在最小的基础上还可以增加多少个
            'RECYCLE': 24 * 60 * 60,  # 连接可以被重复用多久,超过会重新创建,-1表示永久
            'TIMEOUT': 30  # 池中没有现成最多等待的时间
        }
    }

}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
