# Generated by Django 3.2 on 2025-11-04 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_departement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departement',
        ),
    ]
