# Generated by Django 3.2 on 2025-11-04 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pdate',
            field=models.DateField(default=datetime.date.today, verbose_name='注册日期'),
        ),
        migrations.AddField(
            model_name='user',
            name='pdate_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='注册日期及时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=16, verbose_name='姓名'),
        ),
    ]
