# Generated by Django 3.2 on 2025-11-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20251104_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registe_date',
            field=models.DateField(auto_now=True, verbose_name='注册时间'),
        ),
    ]
