# Generated by Django 3.2 on 2025-11-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_registe_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='工资'),
        ),
    ]
